# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 40, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 151, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/ASU_logo.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 720, 771, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(830, 0, 521, 131))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/spotlight_image.jpg"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 170, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.selectionFilePath = QtWidgets.QTextEdit(self.centralwidget)
        self.selectionFilePath.setGeometry(QtCore.QRect(20, 224, 151, 31))
        self.selectionFilePath.setObjectName("selectionFilePath")
        self.BrowseBtnSelection = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseBtnSelection.setEnabled(True)
        self.BrowseBtnSelection.setGeometry(QtCore.QRect(190, 225, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BrowseBtnSelection.setFont(font)
        self.BrowseBtnSelection.setAutoFillBackground(False)
        self.BrowseBtnSelection.setAutoDefault(False)
        self.BrowseBtnSelection.setObjectName("BrowseBtnSelection")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 390, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(93, 431, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(93, 461, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(93, 491, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.cell_1_val = QtWidgets.QLabel(self.centralwidget)
        self.cell_1_val.setGeometry(QtCore.QRect(253, 431, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_1_val.setFont(font)
        self.cell_1_val.setObjectName("cell_1_val")
        self.cell_2_val = QtWidgets.QLabel(self.centralwidget)
        self.cell_2_val.setGeometry(QtCore.QRect(253, 461, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_2_val.setFont(font)
        self.cell_2_val.setObjectName("cell_2_val")
        self.cell_3_val = QtWidgets.QLabel(self.centralwidget)
        self.cell_3_val.setGeometry(QtCore.QRect(253, 491, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_3_val.setFont(font)
        self.cell_3_val.setObjectName("cell_3_val")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 413, 141, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(230, 440, 20, 81))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(40, 195, 331, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 124, 1341, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 700, 1401, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(540, 390, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.cell_5_val = QtWidgets.QLabel(self.centralwidget)
        self.cell_5_val.setGeometry(QtCore.QRect(640, 470, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_5_val.setFont(font)
        self.cell_5_val.setObjectName("cell_5_val")
        self.cell_6_val = QtWidgets.QLabel(self.centralwidget)
        self.cell_6_val.setGeometry(QtCore.QRect(640, 500, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_6_val.setFont(font)
        self.cell_6_val.setObjectName("cell_6_val")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(540, 413, 141, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.cell_4_val = QtWidgets.QLabel(self.centralwidget)
        self.cell_4_val.setGeometry(QtCore.QRect(640, 440, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_4_val.setFont(font)
        self.cell_4_val.setObjectName("cell_4_val")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1000, 380, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(1000, 400, 171, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.cell_HS_11 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_11.setGeometry(QtCore.QRect(1060, 470, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_11.setFont(font)
        self.cell_HS_11.setObjectName("cell_HS_11")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(490, 195, 291, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(496, 170, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.BrowseBtnShading_1 = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseBtnShading_1.setGeometry(QtCore.QRect(660, 220, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BrowseBtnShading_1.setFont(font)
        self.BrowseBtnShading_1.setAutoFillBackground(False)
        self.BrowseBtnShading_1.setObjectName("BrowseBtnShading_1")
        self.shadingFilePath_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.shadingFilePath_1.setGeometry(QtCore.QRect(470, 220, 161, 31))
        self.shadingFilePath_1.setObjectName("shadingFilePath_1")
        self.BrowseBtnShading_2 = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseBtnShading_2.setGeometry(QtCore.QRect(660, 270, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.BrowseBtnShading_2.setFont(font)
        self.BrowseBtnShading_2.setAutoFillBackground(False)
        self.BrowseBtnShading_2.setObjectName("BrowseBtnShading_2")
        self.shadingFilePath_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.shadingFilePath_2.setGeometry(QtCore.QRect(470, 270, 161, 31))
        self.shadingFilePath_2.setObjectName("shadingFilePath_2")
        self.BrowseBtnShading_3 = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseBtnShading_3.setGeometry(QtCore.QRect(660, 320, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.BrowseBtnShading_3.setFont(font)
        self.BrowseBtnShading_3.setAutoFillBackground(False)
        self.BrowseBtnShading_3.setObjectName("BrowseBtnShading_3")
        self.shadingFilePath_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.shadingFilePath_3.setGeometry(QtCore.QRect(470, 320, 161, 31))
        self.shadingFilePath_3.setObjectName("shadingFilePath_3")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(420, 230, 20, 461))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(870, 230, 20, 461))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(950, 170, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(950, 194, 291, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.BrowseBtnHotspot_1 = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseBtnHotspot_1.setGeometry(QtCore.QRect(1120, 220, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.BrowseBtnHotspot_1.setFont(font)
        self.BrowseBtnHotspot_1.setAutoFillBackground(False)
        self.BrowseBtnHotspot_1.setObjectName("BrowseBtnHotspot_1")
        self.hotspotFilePath_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.hotspotFilePath_1.setGeometry(QtCore.QRect(930, 220, 161, 31))
        self.hotspotFilePath_1.setObjectName("hotspotFilePath_1")
        self.cell_HS_21 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_21.setGeometry(QtCore.QRect(1060, 500, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_21.setFont(font)
        self.cell_HS_21.setObjectName("cell_HS_21")
        self.cell_HS_31 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_31.setGeometry(QtCore.QRect(1060, 530, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_31.setFont(font)
        self.cell_HS_31.setObjectName("cell_HS_31")
        self.cell_HS_41 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_41.setGeometry(QtCore.QRect(1060, 560, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_41.setFont(font)
        self.cell_HS_41.setObjectName("cell_HS_41")
        self.cell_HS_51 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_51.setGeometry(QtCore.QRect(1060, 590, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_51.setFont(font)
        self.cell_HS_51.setObjectName("cell_HS_51")
        self.cell_HS_61 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_61.setGeometry(QtCore.QRect(1060, 620, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_61.setFont(font)
        self.cell_HS_61.setObjectName("cell_HS_61")
        self.cell_HS_71 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_71.setGeometry(QtCore.QRect(1060, 650, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_71.setFont(font)
        self.cell_HS_71.setObjectName("cell_HS_71")
        self.cell_HS_81 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_81.setGeometry(QtCore.QRect(1060, 680, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_81.setFont(font)
        self.cell_HS_81.setObjectName("cell_HS_81")
        self.cell_HS_82 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_82.setGeometry(QtCore.QRect(1160, 680, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_82.setFont(font)
        self.cell_HS_82.setObjectName("cell_HS_82")
        self.cell_HS_52 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_52.setGeometry(QtCore.QRect(1160, 590, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_52.setFont(font)
        self.cell_HS_52.setObjectName("cell_HS_52")
        self.cell_HS_22 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_22.setGeometry(QtCore.QRect(1160, 500, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_22.setFont(font)
        self.cell_HS_22.setObjectName("cell_HS_22")
        self.cell_HS_62 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_62.setGeometry(QtCore.QRect(1160, 620, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_62.setFont(font)
        self.cell_HS_62.setObjectName("cell_HS_62")
        self.cell_HS_72 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_72.setGeometry(QtCore.QRect(1160, 650, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_72.setFont(font)
        self.cell_HS_72.setObjectName("cell_HS_72")
        self.cell_HS_42 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_42.setGeometry(QtCore.QRect(1160, 560, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_42.setFont(font)
        self.cell_HS_42.setObjectName("cell_HS_42")
        self.cell_HS_12 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_12.setGeometry(QtCore.QRect(1160, 470, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_12.setFont(font)
        self.cell_HS_12.setObjectName("cell_HS_12")
        self.cell_HS_32 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_32.setGeometry(QtCore.QRect(1160, 530, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_32.setFont(font)
        self.cell_HS_32.setObjectName("cell_HS_32")
        self.cell_HS_33 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_33.setGeometry(QtCore.QRect(1260, 530, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_33.setFont(font)
        self.cell_HS_33.setObjectName("cell_HS_33")
        self.cell_HS_53 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_53.setGeometry(QtCore.QRect(1260, 590, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_53.setFont(font)
        self.cell_HS_53.setObjectName("cell_HS_53")
        self.cell_HS_23 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_23.setGeometry(QtCore.QRect(1260, 500, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_23.setFont(font)
        self.cell_HS_23.setObjectName("cell_HS_23")
        self.cell_HS_63 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_63.setGeometry(QtCore.QRect(1260, 620, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_63.setFont(font)
        self.cell_HS_63.setObjectName("cell_HS_63")
        self.cell_HS_13 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_13.setGeometry(QtCore.QRect(1260, 470, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_13.setFont(font)
        self.cell_HS_13.setObjectName("cell_HS_13")
        self.cell_HS_83 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_83.setGeometry(QtCore.QRect(1260, 680, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_83.setFont(font)
        self.cell_HS_83.setObjectName("cell_HS_83")
        self.cell_HS_73 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_73.setGeometry(QtCore.QRect(1260, 650, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_73.setFont(font)
        self.cell_HS_73.setObjectName("cell_HS_73")
        self.cell_HS_43 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_43.setGeometry(QtCore.QRect(1260, 560, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell_HS_43.setFont(font)
        self.cell_HS_43.setObjectName("cell_HS_43")
        self.cell_HS_14 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_14.setGeometry(QtCore.QRect(1260, 430, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_14.setFont(font)
        self.cell_HS_14.setObjectName("cell_HS_14")
        self.cell_HS_15 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_15.setGeometry(QtCore.QRect(1160, 430, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_15.setFont(font)
        self.cell_HS_15.setObjectName("cell_HS_15")
        self.cell_HS_16 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_16.setGeometry(QtCore.QRect(1060, 430, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_16.setFont(font)
        self.cell_HS_16.setObjectName("cell_HS_16")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(910, 450, 381, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.BrowseBtnHotspot_2 = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseBtnHotspot_2.setGeometry(QtCore.QRect(1120, 270, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.BrowseBtnHotspot_2.setFont(font)
        self.BrowseBtnHotspot_2.setAutoFillBackground(False)
        self.BrowseBtnHotspot_2.setObjectName("BrowseBtnHotspot_2")
        self.hotspotFilePath_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.hotspotFilePath_2.setGeometry(QtCore.QRect(930, 270, 161, 31))
        self.hotspotFilePath_2.setObjectName("hotspotFilePath_2")
        self.BrowseBtnHotspot_3 = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseBtnHotspot_3.setGeometry(QtCore.QRect(1120, 320, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.BrowseBtnHotspot_3.setFont(font)
        self.BrowseBtnHotspot_3.setAutoFillBackground(False)
        self.BrowseBtnHotspot_3.setObjectName("BrowseBtnHotspot_3")
        self.hotspotFilePath_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.hotspotFilePath_3.setGeometry(QtCore.QRect(930, 320, 161, 31))
        self.hotspotFilePath_3.setObjectName("hotspotFilePath_3")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(550, 440, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(603, 450, 20, 71))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(550, 470, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(550, 500, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.cell_HS_17 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_17.setGeometry(QtCore.QRect(910, 470, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_17.setFont(font)
        self.cell_HS_17.setObjectName("cell_HS_17")
        self.cell_HS_18 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_18.setGeometry(QtCore.QRect(910, 500, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_18.setFont(font)
        self.cell_HS_18.setObjectName("cell_HS_18")
        self.cell_HS_19 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_19.setGeometry(QtCore.QRect(910, 530, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_19.setFont(font)
        self.cell_HS_19.setObjectName("cell_HS_19")
        self.cell_HS_20 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_20.setGeometry(QtCore.QRect(910, 560, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_20.setFont(font)
        self.cell_HS_20.setObjectName("cell_HS_20")
        self.cell_HS_24 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_24.setGeometry(QtCore.QRect(910, 590, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_24.setFont(font)
        self.cell_HS_24.setObjectName("cell_HS_24")
        self.cell_HS_25 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_25.setGeometry(QtCore.QRect(910, 620, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_25.setFont(font)
        self.cell_HS_25.setObjectName("cell_HS_25")
        self.cell_HS_26 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_26.setGeometry(QtCore.QRect(910, 650, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_26.setFont(font)
        self.cell_HS_26.setObjectName("cell_HS_26")
        self.cell_HS_27 = QtWidgets.QLabel(self.centralwidget)
        self.cell_HS_27.setGeometry(QtCore.QRect(910, 680, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cell_HS_27.setFont(font)
        self.cell_HS_27.setObjectName("cell_HS_27")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PV HOT-SPOT Automation"))
        self.label_3.setText(_translate("MainWindow", "ASU Photovoltaic Reliability Laboratory (ASU-PRL, established in January 2009) "))
        self.label_5.setText(_translate("MainWindow", "Select Input Data File for Cell Selection:"))
        self.BrowseBtnSelection.setText(_translate("MainWindow", "Cell Selection file"))
        self.label_6.setText(_translate("MainWindow", "Selected Cells:"))
        self.label_7.setText(_translate("MainWindow", "Low Rshunt - Cell 1"))
        self.label_8.setText(_translate("MainWindow", "Low Rshunt - Cell 2"))
        self.label_9.setText(_translate("MainWindow", "Low Rshunt - Cell 3"))
        self.cell_1_val.setText(_translate("MainWindow", "0,0"))
        self.cell_2_val.setText(_translate("MainWindow", "0,0"))
        self.cell_3_val.setText(_translate("MainWindow", "0,0"))
        self.label_10.setText(_translate("MainWindow", "Shading Result:"))
        self.cell_5_val.setText(_translate("MainWindow", "0,0"))
        self.cell_6_val.setText(_translate("MainWindow", "0,0"))
        self.cell_4_val.setText(_translate("MainWindow", "0,0"))
        self.label_11.setText(_translate("MainWindow", "HOT-SPOT Result:"))
        self.cell_HS_11.setText(_translate("MainWindow", "00"))
        self.label_12.setText(_translate("MainWindow", "Select Input Data File for Shading:"))
        self.BrowseBtnShading_1.setText(_translate("MainWindow", "Cell 1 File"))
        self.BrowseBtnShading_2.setText(_translate("MainWindow", "Cell 2 File"))
        self.BrowseBtnShading_3.setText(_translate("MainWindow", "Cell 3 File"))
        self.label_13.setText(_translate("MainWindow", "Select Input Data File for Hot-Spot:"))
        self.BrowseBtnHotspot_1.setText(_translate("MainWindow", "Cell 1 File"))
        self.cell_HS_21.setText(_translate("MainWindow", "00"))
        self.cell_HS_31.setText(_translate("MainWindow", "00"))
        self.cell_HS_41.setText(_translate("MainWindow", "00"))
        self.cell_HS_51.setText(_translate("MainWindow", "00"))
        self.cell_HS_61.setText(_translate("MainWindow", "00"))
        self.cell_HS_71.setText(_translate("MainWindow", "00"))
        self.cell_HS_81.setText(_translate("MainWindow", "00"))
        self.cell_HS_82.setText(_translate("MainWindow", "00"))
        self.cell_HS_52.setText(_translate("MainWindow", "00"))
        self.cell_HS_22.setText(_translate("MainWindow", "00"))
        self.cell_HS_62.setText(_translate("MainWindow", "00"))
        self.cell_HS_72.setText(_translate("MainWindow", "00"))
        self.cell_HS_42.setText(_translate("MainWindow", "00"))
        self.cell_HS_12.setText(_translate("MainWindow", "00"))
        self.cell_HS_32.setText(_translate("MainWindow", "00"))
        self.cell_HS_33.setText(_translate("MainWindow", "00"))
        self.cell_HS_53.setText(_translate("MainWindow", "00"))
        self.cell_HS_23.setText(_translate("MainWindow", "00"))
        self.cell_HS_63.setText(_translate("MainWindow", "00"))
        self.cell_HS_13.setText(_translate("MainWindow", "00"))
        self.cell_HS_83.setText(_translate("MainWindow", "00"))
        self.cell_HS_73.setText(_translate("MainWindow", "00"))
        self.cell_HS_43.setText(_translate("MainWindow", "00"))
        self.cell_HS_14.setText(_translate("MainWindow", "Avg"))
        self.cell_HS_15.setText(_translate("MainWindow", "Min"))
        self.cell_HS_16.setText(_translate("MainWindow", "Max"))
        self.BrowseBtnHotspot_2.setText(_translate("MainWindow", "Cell 2 File"))
        self.BrowseBtnHotspot_3.setText(_translate("MainWindow", "Cell 3 File"))
        self.label_14.setText(_translate("MainWindow", "Cell 1"))
        self.label_15.setText(_translate("MainWindow", "Cell 2"))
        self.label_16.setText(_translate("MainWindow", "Cell 3"))
        self.cell_HS_17.setText(_translate("MainWindow", "T amb"))
        self.cell_HS_18.setText(_translate("MainWindow", "Ref. Cell Voltage"))
        self.cell_HS_19.setText(_translate("MainWindow", "T Cell 1"))
        self.cell_HS_20.setText(_translate("MainWindow", "T Cell 2"))
        self.cell_HS_24.setText(_translate("MainWindow", "T module"))
        self.cell_HS_25.setText(_translate("MainWindow", "Calc. Irradiance"))
        self.cell_HS_26.setText(_translate("MainWindow", "Calc. T rise,cell"))
        self.cell_HS_27.setText(_translate("MainWindow", "Calc. T rise,cell"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

